# Generated by Django 3.1.3 on 2020-11-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_habit_progress'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_habit'),
        ),
    ]
