# Generated by Django 3.1.3 on 2020-11-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201105_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='goal',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='name',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='habit',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
